trigger:
  branches:
    include:
    - releases/*

pr: none

jobs:
- job: EvaluationJob
  timeoutInMinutes: 300
  cancelTimeoutInMinutes: 2

  pool:
    vmImage: 'Ubuntu-20.04'

  steps:
  - script: echo Hello, QA Pipeline!
    displayName: 'QA Pipeline for cgm-ml-service'

  - bash: |
      cd src/common/eval/QA
      source /usr/share/miniconda/etc/profile.d/conda.sh
      conda env create -f environment.yml
      conda activate CGM_QA_Pipeline
      jupyter kernelspec list
    displayName: 'Environment Creation'

  - bash: |
      echo Login Azure Account
      az login -t $(sptenent) --service-principal -u $(spidentity) --password $(spsecret)
      az account set --subscription $(subscriptionid)
    displayName: 'Azure Login'

  - bash: |
      cd src/common/eval/QA
      source /usr/share/miniconda/etc/profile.d/conda.sh
      conda activate CGM_QA_Pipeline
      python auth.py -sid $(subscriptionid) -rg $(RESOURCE_GROUP) -wn $(WORKSPACE_NAME)
    displayName: 'Saving Workspace Config'

  - bash: |
      cd src/common/eval/QA/eval-depthmap-height
      source /usr/share/miniconda/etc/profile.d/conda.sh
      conda activate CGM_QA_Pipeline
      echo Executing eval_notebook.ipynb
      papermill eval_notebook.ipynb depthmap-height_output.ipynb --log-output --no-progress-bar -k python3
      jupyter nbconvert --to html depthmap-height_output.ipynb
      ls -l
    displayName: 'Depthmap Height Model Evaluation'

  - bash: |
      cd src/common/eval/QA/eval-standardisation-test
      source /usr/share/miniconda/etc/profile.d/conda.sh
      conda activate CGM_QA_Pipeline
      echo Executing eval_notebook.ipynb
      papermill eval_notebook.ipynb standardisation-test_output.ipynb --log-output --no-progress-bar -k python3
      jupyter nbconvert --to html standardisation-test_output.ipynb
      ls -l
    displayName: 'Standardisation Test Model Evaluation'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.SourcesDirectory)'
      Contents: |
        src/common/eval/QA/eval-depthmap-height/depthmap-height_output.html
        src/common/eval/QA/eval-depthmap-height/*.csv
        src/common/eval/QA/eval-standardisation-test/standardisation-test_output.html
        src/common/eval/QA/eval-standardisation-test/*.csv
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
    displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'Output Notebook'
      publishLocation: 'pipeline'
    displayName: 'Publish Results and Output Notebook'

  - bash: |
      az logout
    displayName: 'Azure Logout'
